name: .NET CI for NameSorter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v3

    - name: 🧰 Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'  # Adjust if you're using a different SDK

    - name: 📦 Restore dependencies
      run: dotnet restore NameSorter/NameSorter.csproj

    - name: 🛠️ Build solution
      run: dotnet build NameSorter/NameSorter.csproj --no-restore --configuration Release

    - name: 🧪 Run unit tests
      run: dotnet test NameSorter.Tests/NameSorter.Tests.csproj --no-build --configuration Release --verbosity normal
